import type { Meta, StoryObj } from '@storybook/react';
import SettingsProfile from './SettingsProfile';

const meta: Meta<typeof SettingsProfile> = {
  title: 'Pages/SettingsProfile',
  component: SettingsProfile,
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component: 'Settings Profile page with user information, password change, and advanced settings sections. Generated by Artemis Expert using learned patterns from Settings conversion.',
      },
    },
  },
  tags: ['autodocs'],
};

export default meta;
type Story = StoryObj<typeof SettingsProfile>;

export const Default: Story = {
  name: 'Default View',
  parameters: {
    docs: {
      description: {
        story: 'Default settings profile page with all sections visible.',
      },
    },
  },
};

export const MobileView: Story = {
  name: 'Mobile View',
  parameters: {
    viewport: {
      defaultViewport: 'mobile1',
    },
    docs: {
      description: {
        story: 'Settings profile optimized for mobile devices.',
      },
    },
  },
};

export const TabletView: Story = {
  name: 'Tablet View',
  parameters: {
    viewport: {
      defaultViewport: 'tablet',
    },
    docs: {
      description: {
        story: 'Settings profile on tablet screen sizes.',
      },
    },
  },
};

export const FocusedForm: Story = {
  name: 'With Focus States',
  play: async ({ canvasElement }) => {
    const canvas = canvasElement;
    const usernameInput = canvas.querySelector('#username') as HTMLInputElement;
    if (usernameInput) {
      usernameInput.focus();
    }
  },
  parameters: {
    docs: {
      description: {
        story: 'Demonstrates focus states on form inputs.',
      },
    },
  },
};
