'use client';

import React from 'react';
import { Input } from './ui/input';
import { Label } from './ui/label';
import AppLayout from './layout/AppLayout';
import SettingsSidebar from './layout/SettingsSidebar';

/**
 * SettingsProfile Component (REFACTORED)
 *
 * Generated by Artemis Expert (Conversion #2)
 * Based on Figma: https://www.figma.com/design/6Pmf9gCcUccyqbCO9nN6Ts/poc-test?node-id=17-1440
 *
 * NOW USES SHARED COMPONENTS:
 * - AppLayout (header + page structure)
 * - SettingsSidebar (settings navigation)
 *
 * Learned patterns applied:
 * - sidebar-layout (from Settings conversion)
 * - 24px-spacing (enterprise standard)
 * - native-html-for-custom-styles (for Save buttons)
 * - max-w-constrained-content
 * - two-column-form-grid
 *
 * Features:
 * - User profile information form
 * - Password change form
 * - Advanced settings toggles
 * - Responsive sidebar layout
 * - Accessible form controls
 */

export default function SettingsProfile() {
  return (
    <AppLayout currentPage="Settings" showPageHeader={true} pageTitle="Settings">
      {/* Sidebar + Content Layout */}
      <div className="flex gap-6">
        {/* Sidebar - Now using shared component */}
        <SettingsSidebar activePage="Profile" />

        {/* Main Content - Profile Forms */}
        <main className="flex-1">
            <div className="space-y-6">
              {/* Basic Information */}
              <div className="bg-white rounded-lg border border-zinc-200 p-6">
                <h2 className="text-xl font-semibold text-zinc-900 mb-2">Basic information</h2>
                <p className="text-sm text-zinc-500 mb-6">View and update your personal details and account information.</p>

                <div className="space-y-6">
                  <div>
                    <Label htmlFor="username" className="text-sm font-medium text-zinc-900 mb-2 block">
                      Username
                    </Label>
                    <Input
                      id="username"
                      type="text"
                      defaultValue="nicol43"
                      className="w-full"
                    />
                  </div>

                  <div>
                    <Label htmlFor="firstname" className="text-sm font-medium text-zinc-900 mb-2 block">
                      First name
                    </Label>
                    <Input
                      id="firstname"
                      type="text"
                      defaultValue="Stephanie"
                      className="w-full"
                    />
                  </div>

                  <div>
                    <Label htmlFor="lastname" className="text-sm font-medium text-zinc-900 mb-2 block">
                      Last name
                    </Label>
                    <Input
                      id="lastname"
                      type="text"
                      defaultValue="Nicol"
                      className="w-full"
                    />
                  </div>

                  <div>
                    <Label htmlFor="email" className="text-sm font-medium text-zinc-900 mb-2 block">
                      Email address
                    </Label>
                    <Input
                      id="email"
                      type="email"
                      defaultValue="stephanie_nicol@mail.com"
                      className="w-full"
                    />
                  </div>

                  <button className="px-6 py-2 bg-black text-white text-sm font-medium rounded-md hover:bg-zinc-800">
                    Save
                  </button>
                </div>
              </div>

              {/* Change Password */}
              <div className="bg-white rounded-lg border border-zinc-200 p-6">
                <h2 className="text-xl font-semibold text-zinc-900 mb-2">Change password</h2>
                <p className="text-sm text-zinc-500 mb-6">Update your password to keep your account secure.</p>

                <div className="space-y-6">
                  <div>
                    <Label htmlFor="current-password" className="text-sm font-medium text-zinc-900 mb-2 block">
                      Verify current password
                    </Label>
                    <Input
                      id="current-password"
                      type="password"
                      defaultValue="••••••••••"
                      className="w-full"
                    />
                  </div>

                  <div>
                    <Label htmlFor="new-password" className="text-sm font-medium text-zinc-900 mb-2 block">
                      New password
                    </Label>
                    <Input
                      id="new-password"
                      type="password"
                      defaultValue="••••••••••"
                      className="w-full"
                    />
                  </div>

                  <div>
                    <Label htmlFor="confirm-password" className="text-sm font-medium text-zinc-900 mb-2 block">
                      Confirm password
                    </Label>
                    <Input
                      id="confirm-password"
                      type="password"
                      defaultValue="••••••••••"
                      className="w-full"
                    />
                  </div>

                  <button className="px-6 py-2 bg-black text-white text-sm font-medium rounded-md hover:bg-zinc-800">
                    Save
                  </button>
                </div>
              </div>

              {/* Advanced Settings */}
              <div className="bg-white rounded-lg border border-zinc-200 p-6">
                <h2 className="text-xl font-semibold text-zinc-900 mb-2">Advanced settings</h2>
                <p className="text-sm text-zinc-500 mb-6">Configure detailed account preferences and security options.</p>

                <div className="space-y-6">
                  <div className="flex items-start gap-3">
                    <input
                      type="checkbox"
                      id="data-export"
                      defaultChecked
                      className="mt-1 w-4 h-4 rounded border-zinc-300"
                    />
                    <div className="flex-1">
                      <Label htmlFor="data-export" className="text-sm font-medium text-zinc-900 block mb-1 cursor-pointer">
                        Data Export Access
                      </Label>
                      <p className="text-sm text-zinc-500">Allow export of personal data and backups.</p>
                    </div>
                  </div>

                  <div className="flex items-start gap-3">
                    <input
                      type="checkbox"
                      id="admin-members"
                      defaultChecked
                      className="mt-1 w-4 h-4 rounded border-zinc-300"
                    />
                    <div className="flex-1">
                      <Label htmlFor="admin-members" className="text-sm font-medium text-zinc-900 block mb-1 cursor-pointer">
                        Allow Admin to Add Members
                      </Label>
                      <p className="text-sm text-zinc-500">Admins can invite and manage members.</p>
                    </div>
                  </div>

                  <div className="flex items-start gap-3">
                    <input
                      type="checkbox"
                      id="two-factor"
                      defaultChecked
                      className="mt-1 w-4 h-4 rounded border-zinc-300"
                    />
                    <div className="flex-1">
                      <Label htmlFor="two-factor" className="text-sm font-medium text-zinc-900 block mb-1 cursor-pointer">
                        Enable Two-Factor Authentication
                      </Label>
                      <p className="text-sm text-zinc-500">Require 2FA for added account security.</p>
                    </div>
                  </div>

                  <button className="px-6 py-2 bg-black text-white text-sm font-medium rounded-md hover:bg-zinc-800">
                    Save
                  </button>
                </div>
              </div>
            </div>
          </main>
        </div>
      </AppLayout>
  );
}
