import './globals.css';

export const metadata = {
  title: 'Settings Preview',
  description: 'Generated by Artemis Perfect Converter',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const hideNextDevTools = () => {
                  // Target the nextjs-portal element (contains the dev tools in shadow DOM)
                  const portal = document.querySelector('nextjs-portal');
                  if (portal) {
                    portal.style.cssText = 'display: none !important; visibility: hidden !important; opacity: 0 !important;';
                  }
                };

                // Run immediately
                hideNextDevTools();

                // Run after DOM loads
                if (document.readyState === 'loading') {
                  document.addEventListener('DOMContentLoaded', hideNextDevTools);
                } else {
                  setTimeout(hideNextDevTools, 0);
                }

                // Watch for the portal element being added
                const observer = new MutationObserver(hideNextDevTools);
                observer.observe(document.documentElement, {
                  childList: true,
                  subtree: true
                });

                // Also run on load
                window.addEventListener('load', hideNextDevTools);
              })();
            `,
          }}
        />
      </body>
    </html>
  );
}
